#!/bin/bash

LOG_DIR=logs

TEL_WEB_CONTAINER_NAME=local-tel-web-module-1
TEL_WEB_LOG_PATH=/var/log/nginx
TEL_WEB_ACCESS_LOG_FILE=access.log
TEL_WEB_ERROR_LOG_FILE=error.log
TEL_WEB_LOCAL_LOG_FILE_PREFIX=tel-web-module

TEL_TESTDATA_CONTAINER_NAME=local-tel-testdata-module-1
TEL_TESTDATA_LOG_FILE=/app/logs/service.log
TEL_WEB_LOCAL_LOG_FILE=tel-testdata-module.log

mkdir $LOG_DIR

docker cp $TEL_WEB_CONTAINER_NAME:$TEL_WEB_LOG_PATH/$TEL_WEB_ACCESS_LOG_FILE $LOG_DIR/$TEL_WEB_LOCAL_LOG_FILE_PREFIX-$TEL_WEB_ACCESS_LOG_FILE
docker cp $TEL_WEB_CONTAINER_NAME:$TEL_WEB_LOG_PATH/$TEL_WEB_ERROR_LOG_FILE $LOG_DIR/$TEL_WEB_LOCAL_LOG_FILE_PREFIX-$TEL_WEB_ERROR_LOG_FILE
docker cp $TEL_TESTDATA_CONTAINER_NAME:$TEL_TESTDATA_LOG_FILE $LOG_DIR/$TEL_WEB_LOCAL_LOG_FILE

docker compose down
