#!/bin/bash

ALIAS=tes-enterprise-labs

KEY_ALGORITHM=RSA
KEY_SIZE_IN_BITS=2048
KEYSTORE_TYPE=PKCS12
KEYSTORE_FILE=$ALIAS.p12
KEYSTORE_PASSWORD="99oUun9rAvFT7mk/kql696JcAcbM1vtGwtqgK1IFfYjEqG/YXDtOeedCd4v/t0wa"

CERTIFICATE_VALIDITY_IN_DAYS=365

CN="Sune Thomas Poulsen"
ORGANISATION="Private Person"
COMPANY="Private Person"
CITY="Copenhagen"
STATE="Region Hovedstaden"
COUNTRY="DK"
CERTIFICATE_DISTINGUISHED_NAME="CN=$CN, OU=$ORGANISATION, O=$COMPANY, L=$CITY, ST=$STATE, C=$COUNTRY"

SUBJECT_ALTERNATIVE_NAME="SAN=dns:localhost,ip:127.0.0.1"

keytool -genkeypair -alias $ALIAS -keyalg $KEY_ALGORITHM -keysize $KEY_SIZE_IN_BITS -storetype $KEYSTORE_TYPE -validity $CERTIFICATE_VALIDITY_IN_DAYS -keystore $KEYSTORE_FILE -storepass $KEYSTORE_PASSWORD -keypass $KEYSTORE_PASSWORD -dname "$CERTIFICATE_DISTINGUISHED_NAME" -ext "$SUBJECT_ALTERNATIVE_NAME"
